version: '3.8'

services:
  wplacer:
    build: .
    container_name: wplacer
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - wplacer_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wplacer_data:
    driver: local
